--1번 문제
CREATE TABLE TB_CATEGORY(
    NAME VARCHAR2(10),
    USE_YN CHAR(1) NOT NULL
    );
    
--2번 문제   
CREATE TABLE TB_CLASS_TYPE(
    NO VARCHAR(5) PRIMARY KEY NOT NULL,
    NAME VARCHAR2(10) 
    );
    
    
--3번 문제
ALTER TABLE TB_CATEGORY MODIFY NAME VARCHAR2(10) PRIMARY KEY;

--4번 문제
ALTER TABLE TB_CLASS_TYPE MODIFY NAME VARCHAR2(10) NOT NULL;

--5번 문제
ALTER TABLE TB_CATEGORY MODIFY NAME VARCHAR2(20);

ALTER TABLE TB_CLASS_TYPE MODIFY NAME VARCHAR2(20);

ALTER TABLE TB_CLASS_TYPE MODIFY NO VARCHAR(10);

--6번 문제
ALTER TABLE TB_CLASS_TYPE
SET NAME = CAGEGORY_NAME;


    
