-- 1번 문제 
SELECT STUDENT_NO AS "학번" , STUDENT_NAME AS "이름" , ENTRANCE_DATE AS "입학년도"
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002';

-- 2번 문제
SELECT PROFESSOR_NAME, PROFESSOR_SSN FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) > 3 OR LENGTH(PROFESSOR_NAME) < 3
GROUP BY PROFESSOR_NAME, PROFESSOR_SSN 
ORDER BY PROFESSOR_NAME  ASC;

-- 3번 문제 ( 상당히 어렵구먼 ) - 못풀었음
SELECT PROFESSOR_NAME AS "교수이름" ,
EXTRACT(YEAR FROM PROFESSOR_SSN) AS "나이"
FROM TB_PROFESSOR;

-- 4번 문제
SELECT SUBSTR(PROFESSOR_NAME, 2, 5) FROM TB_PROFESSOR;

-- 5번 문제