--9번 문제
SELECT ROUND(AVG(POINT),1) AS "학점" FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';

--10번 문제
SELECT DEPARTMENT_NO AS "학과번호" , COUNT(STUDENT_NAME) AS "학생수"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO ASC;

--11번 문제
SELECT COUNT(*) FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

--12번 문제
SELECT G.TERM_NO AS "년도", ROUND(G.POINT,1) AS "년도별 평점"
FROM TB_GRADE G
JOIN TB_STUDENT S ON G.STUDENT_NO = S.STUDENT_NO
WHERE G.STUDENT_NO = 'A112113' AND STUDENT_NAME = '김고운'
ORDER BY G.TERM_NO ASC;

--13번 문제
SELECT DEPARTMENT_NO AS "학과 코드명", COUNT(ABSENCE_YN) AS "휴학생 수"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO,ABSENCE_YN
HAVING ABSENCE_YN = 'Y'
ORDER BY ABSENCE_YN ASC;