-- 1번 문제
SELECT DEPARTMENT_NAME AS "학과 명", CATEGORY AS "계열" FROM TB_DEPARTMENT;

-- 2번 문제
SELECT DEPARTMENT_NAME AS "학과별", CAPACITY AS "정원" FROM TB_DEPARTMENT;

-- 3번 문제
SELECT S.STUDENT_NAME AS "학생이름", S.ABSENCE_YN AS "휴학여부", D.DEPARTMENT_NAME AS "학과명"
, S.STUDENT_SSN AS "주민등록번호"
FROM TB_STUDENT S 
JOIN TB_DEPARTMENT D ON S.DEPARTMENT_NO = D.DEPARTMENT_NO
WHERE S.ABSENCE_YN = 'Y' AND D.DEPARTMENT_NAME = '국어국문학과' AND S.STUDENT_SSN LIKE '%-2%';

-- 4번 문제
SELECT STUDENT_NAME FROM tb_student
WHERE STUDENT_NO = 'A513079' OR STUDENT_NO = 'A513119' OR STUDENT_NO = 'A513091' OR
STUDENT_NO = 'A513110' OR STUDENT_NO = 'A513090' 
ORDER BY STUDENT_NO DESC;

-- 5번 문제
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30;

SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY >= 20 AND CAPACITY <= 30;

-- 6번 문제 -- 이문제 왜안될까..
SELECT PROFESSOR_NAME FROM TB_PROFESSOR
WHERE DEPARTMENT_NO = NULL;

-- 7번 문제
SELECT STUDENT_NAME FROM TB_STUDENT
WHERE DEPARTMENT_NO = NULL;

-- 8번 문제
