--1번 문제
SELECT STUDENT_NAME AS "학생 이름", STUDENT_ADDRESS AS "주소지"
FROM TB_STUDENT
ORDER BY STUDENT_NAME ASC;

--2번 문제
SELECT STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY STUDENT_SSN DESC;

--3번 문제
SELECT STUDENT_NAME AS "학생 이름", STUDENT_NO AS "학번" , STUDENT_ADDRESS AS "거주지 주소"
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO,1,1) = '9' AND STUDENT_ADDRESS LIKE '%경기도%' OR STUDENT_ADDRESS LIKE '%강원도%'
ORDER BY STUDENT_NAME ASC;

--4번 문제
SELECT PROFESSOR_NAME, PROFESSOR_SSN FROM TB_PROFESSOR
WHERE DEPARTMENT_NO = '005'
ORDER BY PROFESSOR_SSN ASC;

SELECT * FROM TB_DEPARTMENT
WHERE DEPARTMENT_NAME = '법학과';

--5번 문제
SELECT STUDENT_NO , POINT FROM TB_GRADE
WHERE TERM_NO = '200402' AND CLASS_NO = 'C3118100'
ORDER BY POINT DESC;

--6번 문제
SELECT S.STUDENT_NO, S.STUDENT_NAME, D.DEPARTMENT_NAME FROM TB_STUDENT S
JOIN TB_DEPARTMENT D ON S.DEPARTMENT_NO = D.DEPARTMENT_NO
ORDER BY S.STUDENT_NAME DESC;

--7번 문제
SELECT C.CLASS_NAME, D.DEPARTMENT_NAME FROM TB_CLASS C
JOIN TB_DEPARTMENT D ON C.DEPARTMENT_NO = D.DEPARTMENT_NO;

--8번 문제 (코드는 맞는거 같은데 항목 수가 이상함)
SELECT C.CLASS_NAME, P.PROFESSOR_NAME FROM TB_CLASS C
JOIN TB_PROFESSOR P ON C.DEPARTMENT_NO = P.DEPARTMENT_NO;

--9번 문제 (코드는 맞는거 같은데 항목 수가 이상함)
SELECT C.CLASS_NAME, P.PROFESSOR_NAME FROM TB_CLASS C
JOIN TB_PROFESSOR P ON C.DEPARTMENT_NO = P.DEPARTMENT_NO
JOIN TB_DEPARTMENT D ON C.DEPARTMENT_NO = D.DEPARTMENT_NO
WHERE CATEGORY = '인문사회';

--10번 문제
SELECT S.STUDENT_NO AS "학번", S.STUDENT_NAME AS "학생 이름", ROUND(AVG(G.POINT),1) AS "전체 평점"
FROM TB_STUDENT S
JOIN TB_GRADE G ON S.STUDENT_NO = G.STUDENT_NO
WHERE S.DEPARTMENT_NO = '059'
GROUP BY S.STUDENT_NO, S.STUDENT_NAME;

SELECT * FROM TB_DEPARTMENT
WHERE DEPARTMENT_NAME = '음악학과';

--11번 문제
SELECT D.DEPARTMENT_NAME AS "학과이름", S.STUDENT_NAME AS "학생이름", P.PROFESSOR_NAME AS "지도교수이름"
FROM TB_STUDENT S
JOIN TB_DEPARTMENT D ON S.DEPARTMENT_NO = D.DEPARTMENT_NO
JOIN TB_PROFESSOR P ON S.COACH_PROFESSOR_NO = P.PROFESSOR_NO
WHERE S.STUDENT_NO = 'A313047';

SELECT * FROM TB_STUDENT WHERE STUDENT_NO = 'A313047';
SELECT * FROM TB_PROFESSOR WHERE PROFESSOR_NO = 'P034';

--12번 문제
SELECT S.STUDENT_NAME, G.TERM_NO FROM TB_STUDENT S
JOIN TB_GRADE G ON S.STUDENT_NO = G.STUDENT_NO
JOIN TB_CLASS C ON S.DEPARTMENT_NO = C.DEPARTMENT_NO
WHERE C.CLASS_NAME = '인간관계론' AND SUBSTR(G.TERM_NO,1,4) = '2007'; 

--13번 문제 ( 이거 어떻게 풀라는거지 )
SELECT C.CLASS_NAME, D.DEPARTMENT_NAME FROM TB_CLASS C
JOIN TB_DEPARTMENT D ON D.DEPARTMENT_NO = C.DEPARTMENT_NO
JOIN TB_CLASS_PROFESSOR P ON C.CLASS_NO = P.CLASS_NO
WHERE D.CATEGORY = '예체능';

--14번 문제 ( 지도교수 미지정 안돼있음 )
SELECT S.STUDENT_NAME AS "학생이름", P.PROFESSOR_NAME AS "지도교수"
FROM TB_STUDENT S
JOIN TB_PROFESSOR P ON S.COACH_PROFESSOR_NO = P.PROFESSOR_NO
WHERE S.DEPARTMENT_NO = '020' 
ORDER BY S.STUDENT_NO ASC;

--15번 문제 ( 왜이렇게 많이나올까 )
SELECT S.STUDENT_NO AS "학번", S.STUDENT_NAME AS "이름", D.DEPARTMENT_NAME AS "학과 이름",AVG(G.POINT) AS "평점"
FROM TB_STUDENT S
JOIN TB_DEPARTMENT D ON S.DEPARTMENT_NO = D.DEPARTMENT_NO
JOIN TB_GRADE G ON S.STUDENT_NO = G.STUDENT_NO
WHERE G.POINT >= 4.0 AND S.ABSENCE_YN = 'N'
GROUP BY S.STUDENT_NO, S.STUDENT_NAME, D.DEPARTMENT_NAME
ORDER BY S.STUDENT_NO ASC;

--16번 문제 
SELECT C.CLASS_NO, C.CLASS_NAME, AVG(G.POINT)
FROM TB_CLASS C
JOIN TB_DEPARTMENT D ON C.DEPARTMENT_NO = D.DEPARTMENT_NO
JOIN TB_GRADE G ON C.CLASS_NO = G.CLASS_NO
WHERE D.DEPARTMENT_NAME = '환경조경학과'
GROUP BY C.CLASS_NO, C.CLASS_NAME;

--17번 문제 ( 안 풀었음 )
--SELECT S.STUDENT_NAME, S.STUDENT_ADDRESS FROM TB_STUDENT S

--18번 문제 ( 왜이렇게 많이나오지?)
SELECT S.STUDENT_NO, S.STUDENT_NAME FROM TB_STUDENT S
JOIN TB_GRADE G ON S.STUDENT_NO = G.STUDENT_NO
JOIN TB_DEPARTMENT D ON S.DEPARTMENT_NO = D.DEPARTMENT_NO
WHERE G.POINT = (SELECT MAX(G.POINT) FROM TB_GRADE G WHERE D.DEPARTMENT_NAME = '국어국문학과');

--19번 문제 ( 안풀었음)