CREATE TABLE USER_INFO 
(
  USER_ID NUMBER(5, 0) 
, USER_NAME VARCHAR2(20 BYTE) 
, USER_EMAIL VARCHAR2(20 BYTE) 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

COMMENT ON COLUMN USER_INFO.USER_ID IS '저장된 순서';

COMMENT ON COLUMN USER_INFO.USER_NAME IS '유저이름';

COMMENT ON COLUMN USER_INFO.USER_EMAIL IS '유저 이메일';
