--1번 문제
SELECT student_no AS "학번", student_name AS "이름", entrance_date AS "입학년도"
from tb_student 
WHERE DEPARTMENT_NO = 002
ORDER BY DEPARTMENT_NO ASC;



--2번 문제
SELECT PROFESSOR_NAME AS "교수이름", PROFESSOR_SSN AS "주민등록번호"
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) > 3 OR LENGTH(PROFESSOR_NAME) < 3
ORDER BY PROFESSOR_NAME ASC;


--3번 문제
SELECT PROFESSOR_NAME AS "교수이름", 2008 - (19||SUBSTR(PROFESSOR_SSN,1,2)) AS "나이"
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN,8,1) = 1
ORDER BY 나이 ASC;


--4번 문제
SELECT SUBSTR(PROFESSOR_NAME,2,3) AS "이름"
FROM TB_PROFESSOR;


--5번 문제 ( 내 생각엔 맞는 풀이 방식인데 답 이 다름 )
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN, ENTRANCE_DATE
FROM TB_STUDENT
WHERE ((20||SUBSTR(ENTRANCE_DATE,1,2)) - (19||SUBSTR(STUDENT_SSN,1,2))) > 19
ORDER BY STUDENT_NO DESC ;



--6번 문제 ( 못풀음 )
SELECT TIMESTAMP(TO_DATE('2020-12-25',('YYYY-MM-DD'));

--7번 문제 ( 못풀음)
--1999-10-11/1949-10-11

--8번 문제
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE ((20||SUBSTR(ENTRANCE_DATE,1,2)) - (19||SUBSTR(STUDENT_SSN,1,2))) > 20
ORDER BY STUDENT_NAME;

--